@echo off
chcp 65001 >nul
cd /d "%~dp0"
setlocal enabledelayedexpansion

echo ==========================================
echo   地推商圈分析 - 一键启动
echo ==========================================
echo.

rem ============ 1. 找 Python ============
set "PY="
set "PYWHERE="
if exist ".venv\Scripts\python.exe" (
    set "PY=.venv\Scripts\python.exe"
    set "PYWHERE=虚拟环境 .venv"
)
if not defined PY (
    py -3 --version >nul 2>&1
    if not errorlevel 1 (
        set "PY=py -3"
        set "PYWHERE=Python 启动器 py -3"
    )
)
if not defined PY (
    python --version >nul 2>&1
    if not errorlevel 1 (
        set "PY=python"
        set "PYWHERE=系统 python"
    )
)
if not defined PY goto :no_python

echo [1/4] Python: !PYWHERE!

rem ============ 2. 按需装依赖 ============
rem 拿 requirements.txt 和上次装成功时存的副本比对，一样就跳过，
rem 免得每次启动都白等 pip 跑一遍。
set "NEED_DEPS=1"
if exist ".deps.lock" (
    fc /b ".deps.lock" "requirements.txt" >nul 2>&1
    if not errorlevel 1 set "NEED_DEPS=0"
)
if "!NEED_DEPS!"=="1" (
    echo [2/4] 安装依赖（第一次会慢一点，之后会跳过）...
    !PY! -m pip install -r requirements.txt
    if errorlevel 1 goto :pip_failed
    copy /y "requirements.txt" ".deps.lock" >nul
) else (
    echo [2/4] 依赖已是最新，跳过
)

rem ============ 3. 首次运行时配 key ============
if exist ".env" (
    echo [3/4] 已有 .env，保持不动
) else (
    call :make_env
)

rem ============ 4. 读端口并启动 ============
set "PORT=8000"
for /f "usebackq tokens=1,* delims==" %%a in (`findstr /b /i /c:"PORT=" ".env" 2^>nul`) do set "PORT=%%b"
rem 万一取到的值不是纯数字（比如行尾混进了回车），退回默认端口，
rem 免得拼出一个打不开的网址
set "PORTOK="
echo !PORT!| findstr /r /c:"^[0-9][0-9]*$" >nul && set "PORTOK=1"
if not defined PORTOK set "PORT=8000"

echo [4/4] 启动服务...
echo.
echo   ------------------------------------------------
echo    浏览器会自动打开   http://localhost:!PORT!
echo    没自动打开就手动访问上面这个地址
echo    要停止服务：按 Ctrl+C，或直接关掉这个窗口
echo   ------------------------------------------------
echo.

rem 服务是阻塞的前台进程，所以先派一个后台任务等几秒再开浏览器。
rem 这里用 ping 当延时而不是 timeout —— timeout 在后台进程里
rem 会因为拿不到标准输入而报错。
start "" /b cmd /c "ping -n 6 127.0.0.1 >nul & start http://localhost:!PORT!"

!PY! -m backend.main

echo.
echo 服务已停止。
pause
exit /b 0


rem ================= 子过程 =================

:make_env
echo [3/4] 第一次运行，配一下 key
echo.
echo    两个都是免费的。现在还没申请就直接回车跳过 --
echo    服务照样能启动，网页左上角会告诉你去哪申请。
echo.
echo    [1] 腾讯位置服务（抓店铺数据，10000 次/日）
echo        https://lbs.qq.com/dev/console/key/manage
echo        建 key 时勾选 WebServiceAPI，域名白名单留空
set "TKEY="
set /p "TKEY=        粘贴 key 后回车: "
echo.
echo    [2] 天地图（地图底图，10000 次/日）
echo        https://console.tianditu.gov.cn/api/key
echo        类型选「浏览器端」
set "DKEY="
set /p "DKEY=        粘贴 key 后回车: "
echo.

rem 生成的 .env 全部保持 ASCII，避免不同 Windows 代码页下的编码问题。
rem 中文默认值（比如 DEFAULT_CITY=长沙）在 config.py 里本来就是默认值，
rem 不写进来反而更稳。想调其他项看 .env.example。
> ".env" echo # generated by run.bat -- see .env.example for all options
>> ".env" echo POI_PROVIDER=auto
>> ".env" echo TENCENT_KEY=!TKEY!
>> ".env" echo MAP_PROVIDER=tianditu
>> ".env" echo TIANDITU_KEY=!DKEY!
>> ".env" echo LLM_PROVIDER=none
>> ".env" echo LABOR_THRESHOLD=60
>> ".env" echo GRID_SIZE_M=800
>> ".env" echo PORT=8000

if not defined TKEY (
    echo    已生成 .env（key 留空了，网页上会提示你去申请）
) else (
    echo    已生成 .env
)
echo.
goto :eof


:no_python
echo.
echo [错误] 没找到 Python。
echo.
echo 去 https://www.python.org/downloads/ 装一个（建议 3.10 以上），
echo 安装时记得勾上「Add Python to PATH」，然后重新双击本脚本。
echo.
pause
exit /b 1

:pip_failed
echo.
echo [错误] 依赖安装失败，具体原因看上面 pip 的报错。
echo.
echo 最常见的是网络问题，可以试试换国内源，在这个窗口里执行：
echo     !PY! -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
echo.
pause
exit /b 1
